# set server to use the conventional port that the config server is expected to run on
server:
  port: 8888

# Point the config server at the git repo containing the configuration settings
spring:
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/macsux/pcf-ers-dotnetcore-workshop.git
          searchPaths: config
#          uri: ${user.dir}\..\config
        native:
          searchLocations: file:..\config,file:..\config\{label}
